version: "3"
services:
    react:
        container_name: react
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
