AWSTemplateFormatVersion: "2010-09-09"
Description: S3 and CloudFront for Static website hosting

# Metadata:
#   "AWS::CloudFormation::Interface":
#     ParameterGroups:
#       - Label:
#           default: "S3 and CloudFront Configuration"
#         Parameters:
#           - WebsiteDomainName
#           - ACMSSLCertificateARN
#           - HostedZoneId

#     ParameterLabels:
#       WebsiteDomainName:
#         default: "WebsiteDomainName"
#       ACMSSLCertificateARN:
#         default: "ACMSSLCertificateARN"
#       HostedZoneId:
#         default: "HostedZoneId"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  SecretsManagerName:
    Type: String

Resources:
  # ------------------------------------------------------------#
  #  S3 Bucket
  # ------------------------------------------------------------#
  # Bucket
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:WEBSITE_DOMAIN_NAME}}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}

  # ------------------------------------------------------------#
  #  CloudFront
  # ------------------------------------------------------------#
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:WEBSITE_DOMAIN_NAME}}"
        DefaultRootObject: "/index.html"
        PriceClass: PriceClass_All
        Origins:
          - DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
            Id: !Join
              - ""
              - - "S3-Website-"
                - !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:WEBSITE_DOMAIN_NAME}}"
                - ".s3-website-ap-northeast-1.amazonaws.com"
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          TargetOriginId: !Join
            - ""
            - - "S3-Website-"
              - !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:WEBSITE_DOMAIN_NAME}}"
              - ".s3-website-ap-northeast-1.amazonaws.com"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          DefaultTTL: 3600
          MaxTTL: 86400
          MinTTL: 60
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
          AcmCertificateArn: !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:ACM_SSL_CERTIFICATE_ARN}}"
        HttpVersion: http2
        Enabled: true

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        "Comment": !Ref Bucket

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:HOSTED_ZONE_ID}}"
      Name: !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:WEBSITE_DOMAIN_NAME}}"
      Type: A
      AliasTarget:
        HostedZoneId: !Sub "{{resolve:secretsmanager:${SecretsManagerName}:SecretString:HOSTED_ZONE_ID}}"
        DNSName: !GetAtt CloudFrontDistribution.DomainName

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  #WebsiteURL:
  WebsiteURL:
    Value: !GetAtt Bucket.WebsiteURL

  #DistributionID
  DistributionID:
    Value: !Ref CloudFrontDistribution

  #DmainName
  DomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName

  #DmainName
  DNSRecord:
    Value: !Ref DNSRecord
